// Marketplace → Detection rules catalog (mock).
// Each rule is mapped to the parser whose parsed events it evaluates, so the
// "Associated parser" column is realistic (e.g. AWS CloudTrail rules → AWS.CloudTrail).

export type DetectionSeverity = "Critical" | "High" | "Medium" | "Low" | "Informational"

export type DetectionRule = {
  name: string
  /** Parser this rule evaluates events from. */
  parser: string
  severity: DetectionSeverity
  tactic: string
  technique: string
  techniqueId: string
  pack: string
}

// Realistic datasource instance name that would produce each parser's events.
const PARSER_DATASOURCE: Record<string, string> = {
  "Databricks.Audit": "databricks-audit-prod",
  "Okta.SystemLog": "okta-corp",
  "AWS.CloudTrail": "aws-cloudtrail-org",
  "AWS.GuardDuty": "aws-guardduty-prod",
  "AWS.VPCFlow": "aws-vpcflow-prod",
  "AzureAD.SignInLogs": "entra-signin-logs",
  "GCP.AuditLog": "gcp-audit-org",
  "GitHub.AuditLog": "github-enterprise",
  "Kubernetes.Audit": "eks-audit-prod",
  "Slack.AuditLogs": "slack-enterprise",
}

/**
 * Connected datasource for a rule's parser, or `null` when no datasource in the
 * workspace is wired to that parser. Deterministic so ~20% of rules return null.
 */
export function connectedDatasource(rule: DetectionRule): string | null {
  let hash = 0
  for (const char of rule.name) hash = (hash * 31 + char.charCodeAt(0)) >>> 0
  if (hash % 5 === 0) return null
  return PARSER_DATASOURCE[rule.parser] ?? null
}

export const DETECTION_RULES: DetectionRule[] = [
  {
    name: "acl_controls_disabled",
    parser: "Databricks.Audit",
    severity: "High",
    tactic: "Defense Evasion",
    technique: "Impair Defenses",
    techniqueId: "T1562",
    pack: "Databricks Audit Intelligence",
  },
  {
    name: "anomalous_user_agent_change",
    parser: "Okta.SystemLog",
    severity: "Medium",
    tactic: "Initial Access",
    technique: "Valid Accounts",
    techniqueId: "T1078",
    pack: "Initial Access Behavior Detections",
  },
  {
    name: "attempted_login_from_denied_ip",
    parser: "Databricks.Audit",
    severity: "Informational",
    tactic: "Initial Access",
    technique: "Valid Accounts",
    techniqueId: "T1078",
    pack: "Databricks Audit Intelligence",
  },
  {
    name: "aws_bedrock_model_abuse",
    parser: "AWS.CloudTrail",
    severity: "Medium",
    tactic: "Impact",
    technique: "Resource Hijacking",
    techniqueId: "T1496",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_cloudtrail_logging_disabled",
    parser: "AWS.CloudTrail",
    severity: "High",
    tactic: "Defense Evasion",
    technique: "Impair Defenses",
    techniqueId: "T1562",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_cloudtrail_logging_modified",
    parser: "AWS.CloudTrail",
    severity: "Medium",
    tactic: "Defense Evasion",
    technique: "Impair Defenses",
    techniqueId: "T1562",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_config_recording_disabled",
    parser: "AWS.CloudTrail",
    severity: "High",
    tactic: "Defense Evasion",
    technique: "Impair Defenses",
    techniqueId: "T1562",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_console_login_bruteforce",
    parser: "AWS.CloudTrail",
    severity: "Medium",
    tactic: "Credential Access",
    technique: "Brute Force",
    techniqueId: "T1110",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_cryptomining_instance_launch",
    parser: "AWS.CloudTrail",
    severity: "Medium",
    tactic: "Impact",
    technique: "Resource Hijacking",
    techniqueId: "T1496",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_ebs_snapshot_shared_external",
    parser: "AWS.CloudTrail",
    severity: "High",
    tactic: "Exfiltration",
    technique: "Transfer Data to Cloud Account",
    techniqueId: "T1537",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_ec2_startup_script_change",
    parser: "AWS.CloudTrail",
    severity: "High",
    tactic: "Persistence",
    technique: "Boot or Logon Initialization Scripts",
    techniqueId: "T1037",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_eks_public_endpoint",
    parser: "AWS.CloudTrail",
    severity: "High",
    tactic: "Initial Access",
    technique: "Exploit Public-Facing Application",
    techniqueId: "T1190",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_guardduty_disabled",
    parser: "AWS.CloudTrail",
    severity: "High",
    tactic: "Defense Evasion",
    technique: "Impair Defenses",
    techniqueId: "T1562",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_guardduty_high_severity_finding",
    parser: "AWS.GuardDuty",
    severity: "High",
    tactic: "",
    technique: "",
    techniqueId: "",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_guardduty_ip_allowlist_created",
    parser: "AWS.CloudTrail",
    severity: "High",
    tactic: "Defense Evasion",
    technique: "Impair Defenses",
    techniqueId: "T1562",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_guardduty_settings_modified",
    parser: "AWS.CloudTrail",
    severity: "Medium",
    tactic: "Defense Evasion",
    technique: "Impair Defenses",
    techniqueId: "T1562",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_iam_access_key_created",
    parser: "AWS.CloudTrail",
    severity: "High",
    tactic: "Persistence",
    technique: "Account Manipulation",
    techniqueId: "T1098",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_iam_account_enumeration",
    parser: "AWS.CloudTrail",
    severity: "Medium",
    tactic: "Discovery",
    technique: "Account Discovery",
    techniqueId: "T1087",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_iam_identity_provider_changed",
    parser: "AWS.CloudTrail",
    severity: "Medium",
    tactic: "Persistence",
    technique: "Modify Authentication Process",
    techniqueId: "T1556",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_iam_privesc_policy_attached",
    parser: "AWS.CloudTrail",
    severity: "High",
    tactic: "Privilege Escalation",
    technique: "Account Manipulation",
    techniqueId: "T1098",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_vpc_flow_port_scan",
    parser: "AWS.VPCFlow",
    severity: "Medium",
    tactic: "Discovery",
    technique: "Network Service Discovery",
    techniqueId: "T1046",
    pack: "Amazon Web Services",
  },
  {
    name: "aws_s3_public_bucket_policy",
    parser: "AWS.CloudTrail",
    severity: "High",
    tactic: "Exfiltration",
    technique: "Transfer Data to Cloud Account",
    techniqueId: "T1537",
    pack: "Amazon Web Services",
  },
  {
    name: "okta_mfa_deactivated",
    parser: "Okta.SystemLog",
    severity: "High",
    tactic: "Defense Evasion",
    technique: "Impair Defenses",
    techniqueId: "T1562",
    pack: "Okta Identity",
  },
  {
    name: "okta_admin_role_assigned",
    parser: "Okta.SystemLog",
    severity: "Medium",
    tactic: "Privilege Escalation",
    technique: "Account Manipulation",
    techniqueId: "T1098",
    pack: "Okta Identity",
  },
  {
    name: "okta_impossible_travel",
    parser: "Okta.SystemLog",
    severity: "High",
    tactic: "Initial Access",
    technique: "Valid Accounts",
    techniqueId: "T1078",
    pack: "Okta Identity",
  },
  {
    name: "entra_conditional_access_modified",
    parser: "AzureAD.SignInLogs",
    severity: "High",
    tactic: "Defense Evasion",
    technique: "Impair Defenses",
    techniqueId: "T1562",
    pack: "Microsoft Entra ID",
  },
  {
    name: "entra_legacy_auth_success",
    parser: "AzureAD.SignInLogs",
    severity: "Medium",
    tactic: "Initial Access",
    technique: "Valid Accounts",
    techniqueId: "T1078",
    pack: "Microsoft Entra ID",
  },
  {
    name: "gcp_service_account_key_created",
    parser: "GCP.AuditLog",
    severity: "Medium",
    tactic: "Persistence",
    technique: "Account Manipulation",
    techniqueId: "T1098",
    pack: "Google Cloud Platform",
  },
  {
    name: "gcp_firewall_rule_deleted",
    parser: "GCP.AuditLog",
    severity: "Medium",
    tactic: "Defense Evasion",
    technique: "Impair Defenses",
    techniqueId: "T1562",
    pack: "Google Cloud Platform",
  },
  {
    name: "github_org_member_removed",
    parser: "GitHub.AuditLog",
    severity: "Low",
    tactic: "Impact",
    technique: "Account Access Removal",
    techniqueId: "T1531",
    pack: "GitHub",
  },
  {
    name: "github_branch_protection_disabled",
    parser: "GitHub.AuditLog",
    severity: "High",
    tactic: "Defense Evasion",
    technique: "Impair Defenses",
    techniqueId: "T1562",
    pack: "GitHub",
  },
  {
    name: "k8s_privileged_pod_created",
    parser: "Kubernetes.Audit",
    severity: "High",
    tactic: "Privilege Escalation",
    technique: "Escape to Host",
    techniqueId: "T1611",
    pack: "Kubernetes",
  },
  {
    name: "slack_admin_role_change",
    parser: "Slack.AuditLogs",
    severity: "Medium",
    tactic: "Privilege Escalation",
    technique: "Account Manipulation",
    techniqueId: "T1098",
    pack: "Slack",
  },
  {
    name: "slack_data_export_enabled",
    parser: "Slack.AuditLogs",
    severity: "High",
    tactic: "Collection",
    technique: "Data from Information Repositories",
    techniqueId: "T1213",
    pack: "Slack",
  },
]
