export type DetectionSeverity = "Critical" | "High" | "Medium" | "Low" | "Informational"
export type DetectionFidelity = "High" | "Medium" | "Low"

export type DetectionRuleListItem = {
  id: string
  name: string
  location: string
  description: string
  severity: DetectionSeverity
  lastModified: string
  category: string
  fidelity: DetectionFidelity
  annotations: string[]
  active: boolean
}

export const DETECTION_RULES_LIST: DetectionRuleListItem[] = [
  {
    id: "unauthorized-s3-bucket-access",
    name: "Unauthorized S3 Bucket Access",
    location: "AWS CloudTrail",
    description: "Detects when an S3 bucket policy is changed to allow public access.",
    severity: "High",
    lastModified: "2 hours ago",
    category: "Exfiltration",
    fidelity: "High",
    annotations: ["prod", "soc-priority"],
    active: true,
  },
  {
    id: "excessive-okta-login-failures",
    name: "Excessive Login Failures (Okta)",
    location: "Okta Logs",
    description: "Flags more than 10 failed logins for one user in 5 minutes.",
    severity: "Medium",
    lastModified: "Sep 1, 2026",
    category: "Identity",
    fidelity: "High",
    annotations: ["prod"],
    active: true,
  },
  {
    id: "massive-data-export-external-ip",
    name: "Massive Data Export to External IP",
    location: "VPC Flow Logs",
    description: "Detects large outbound transfers to destinations outside known CIDR ranges.",
    severity: "Critical",
    lastModified: "3 days ago",
    category: "Exfiltration",
    fidelity: "Medium",
    annotations: ["soc-priority"],
    active: true,
  },
  {
    id: "new-admin-role-assigned",
    name: "New Admin Role Assigned",
    location: "Databricks Audit Logs",
    description: "Detects assignment of workspace admin privileges to a user or service principal.",
    severity: "High",
    lastModified: "Sep 2, 2026",
    category: "Persistence",
    fidelity: "High",
    annotations: ["prod", "compliance:hipaa"],
    active: true,
  },
  {
    id: "mfa-deactivated",
    name: "MFA Bypass or Deactivation",
    location: "Okta Logs",
    description: "Detects when multifactor authentication is disabled for a user account.",
    severity: "High",
    lastModified: "6 hours ago",
    category: "Defense Evasion",
    fidelity: "High",
    annotations: ["soc-priority"],
    active: true,
  },
  {
    id: "cloudtrail-logging-disabled",
    name: "CloudTrail Logging Disabled",
    location: "AWS CloudTrail",
    description: "Detects StopLogging or DeleteTrail API calls against organization trails.",
    severity: "Critical",
    lastModified: "Aug 28, 2026",
    category: "Defense Evasion",
    fidelity: "High",
    annotations: ["prod"],
    active: true,
  },
  {
    id: "impossible-travel-login",
    name: "Impossible Travel Login",
    location: "Azure AD Sign-In Logs",
    description: "Flags authentications from distant geographies within a short time window.",
    severity: "Medium",
    lastModified: "1 day ago",
    category: "Initial Access",
    fidelity: "Medium",
    annotations: ["prod"],
    active: true,
  },
  {
    id: "gcp-service-account-key-created",
    name: "Service Account Key Created",
    location: "GCP Audit Log",
    description: "Detects creation of a new service account key in a production project.",
    severity: "High",
    lastModified: "Sep 3, 2026",
    category: "Credential Access",
    fidelity: "High",
    annotations: ["compliance:hipaa"],
    active: false,
  },
  {
    id: "github-org-owner-added",
    name: "GitHub Organization Owner Added",
    location: "GitHub Audit Log",
    description: "Detects addition of a new owner to the GitHub organization.",
    severity: "Medium",
    lastModified: "5 days ago",
    category: "Persistence",
    fidelity: "Medium",
    annotations: ["prod"],
    active: true,
  },
  {
    id: "k8s-privileged-pod-created",
    name: "Privileged Pod Created",
    location: "Kubernetes Audit",
    description: "Detects pods started with privileged: true in production namespaces.",
    severity: "High",
    lastModified: "12 hours ago",
    category: "Privilege Escalation",
    fidelity: "Medium",
    annotations: ["soc-priority"],
    active: true,
  },
  {
    id: "slack-token-exfiltration",
    name: "Slack Token Exfiltration",
    location: "Slack Audit Logs",
    description: "Detects export or copy of workspace tokens and secrets from Slack.",
    severity: "Low",
    lastModified: "Aug 20, 2026",
    category: "Exfiltration",
    fidelity: "Low",
    annotations: ["prod"],
    active: true,
  },
  {
    id: "guardduty-high-severity-finding",
    name: "GuardDuty High-Severity Finding",
    location: "AWS GuardDuty",
    description: "Surfaces GuardDuty findings rated High or Critical for SOC triage.",
    severity: "Informational",
    lastModified: "4 hours ago",
    category: "Initial Access",
    fidelity: "High",
    annotations: ["prod"],
    active: true,
  },
]
